
using System;

namespace SCaddins.RenameUtilities
{
    /// <summary>
    /// Description of Class1.
    /// </summary>
    public class RenameManager
    {
        public RenameManager()
        {
        }
        
//        public static List<RenameCandidate> GetRoomParameters(){
//            List<RenameCandidate> candidates = new List<RenameCandidate>();
//            FilteredElementCollector collector = new FilteredElementCollector(doc);
//            collector.OfCategory(BuiltInCategory.OST_Rooms);
//            foreach (SpatialElement view in collector) {
//                var p = view.GetParameters("Name");
//                if (p.Count > 0) {
//                    candidates.Add(new RenameCandidate(p[0]));
//                }
//            }
//        }
        
    }
}
